services:
  database:
    image: bitnami/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tripwise
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync+restart
        - path: .
          target: /app
          action: sync+restart
    environment:
      DATABASE_URL: "mysql://root:root@database:3306/tripwise"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    